
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'MundoToggle'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = { n = '<Plug>' }
hook_source = '''
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to â†’ '
    let g:EasyMotion_keys = 'fjdkswbeoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = [
      'html',
      'css',
      'javascript',
      'javascriptreact',
      'go',
      'python',
      'lua',
      'rust',
      'vim',
      'less',
      'stylus',
      'sass',
      'scss',
      'json',
      'ruby',
      'toml',
    ]
hook_source = '''
	let g:rainbow_active = 0
'''


[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = ['FloatermNew', 'FloatermToggle', 'FloatermPrev', 'FloatermNext', 'FloatermSend']
hook_source= '''
    let g:floaterm_position = 'center'
    let g:floaterm_wintype = 'floating'

    " Set floaterm window's background to black
    hi Floaterm guibg=black
    " Set floating window border line color to cyan, and background to orange
    hi FloatermBorder guibg=none guifg=cyan
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''


[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = 'Goyo'
hook_source = '''
		source  $VIM_PATH/vim-modules/module-goyo.vim
'''

[[plugins]]
repo = 'junegunn/Limelight.vim'
on_cmd = 'Limelight'
hook_add = '''
  let g:limelight_conceal_ctermfg = 'gray'
  let g:limelight_conceal_ctermfg = 240
  let g:limelight_conceal_guifg = 'DarkGray'
  let g:limelight_conceal_guifg = '#777777'
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'brooth/far.vim'

# [[plugins]]
# repo = 'danilamihailov/beacon.nvim'

# [[plugins]]
# repo = 'itchyny/vim-cursorword'

# [[plugins]]
# repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'Yggdroot/hiPairs'
